backend:
  name: git-gateway
  branch: main
media_folder: "assets"
public_folder: "/assets"
locale: "el"
collections:
  - name: "content"
    label: "Περιεχόμενο"
    files:
      - file: "content/site.json"
        label: "Site (Brand, Images, CTA, Taglines)"
        name: "site"
        fields:
          - {label: "Brand", name: "brand", widget: "string"}
          - label: "Images"
            name: "images"
            widget: "object"
            fields:
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Cover", name: "cover", widget: "image"}
              - {label: "Couple (PNG)", name: "couple", widget: "image"}
          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - {label: "Τηλέφωνο", name: "phone", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Διεύθυνση", name: "address", widget: "string"}
          - {label: "Taglines", name: "taglines", widget: "list", field: {label: "Φράση", name: "phrase", widget: "string"}}

      - file: "content/hero.json"
        label: "Hero"
        name: "hero"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Τίτλος", name: "title", widget: "string"}
              - {label: "Υπότιτλος", name: "subtitle", widget: "text"}
              - {label: "Lead (δέχεται HTML)", name: "lead", widget: "text"}
              - {label: "Chips", name: "chips", widget: "list", field: {label: "Item", name: "item", widget: "string"}}

      - file: "content/about.json"
        label: "About"
        name: "about"
        fields:
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - {label: "Τίτλος", name: "title", widget: "string"}
              - {label: "Κείμενο 1", name: "p1", widget: "text"}
              - {label: "Κείμενο 2", name: "p2", widget: "text"}
              - {label: "Κείμενο 3", name: "p3", widget: "text"}

      - file: "content/gallery.json"
        label: "Gallery"
        name: "gallery"
        fields:
          - {label: "Gallery", name: "gallery", widget: "list", fields: [
              {label: "Εικόνα", name: "src", widget: "image"},
              {label: "Alt κείμενο", name: "alt", widget: "string"}
            ]}

      - file: "content/videos.json"
        label: "Videos"
        name: "videos"
        fields:
          - {label: "Videos", name: "videos", widget: "list", fields: [
              {label: "Τίτλος", name: "title", widget: "string"},
              {label: "YouTube URL ή ID", name: "url", widget: "string"}
            ]}

      - file: "content/form.json"
        label: "Φόρμα Επικοινωνίας"
        name: "form"
        fields:
          - label: "Form"
            name: "form"
            widget: "object"
            fields:
              - {label: "Ενεργή", name: "enabled", widget: "boolean", default: true}
              - {label: "Τίτλος", name: "title", widget: "string"}
              - {label: "Υπότιτλος", name: "subtitle", widget: "string"}
              - {label: "Μήνυμα επιτυχίας", name: "success", widget: "string"}
              - label: "Πεδία"
                name: "fields"
                widget: "object"
                fields:
                  - {label: "Ονοματεπώνυμο", name: "name_label", widget: "string"}
                  - {label: "Email", name: "email_label", widget: "string"}
                  - {label: "Τηλέφωνο", name: "phone_label", widget: "string"}
                  - {label: "Μήνυμα", name: "message_label", widget: "string"}
                  - {label: "Συναίνεση", name: "consent_label", widget: "string"}
                  - {label: "Κουμπί Υποβολής", name: "submit_label", widget: "string"}
