backend:
  name: git-gateway
  branch: main
media_folder: "assets"
public_folder: "/assets"
locale: "el"
collections:
  - name: "site"
    label: "Περιεχόμενο"
    files:
      - file: "content.json"
        label: "Content"
        name: "content"
        fields:
          - {label: "Brand", name: "brand", widget: "string"}
          - label: "Images"
            name: "images"
            widget: "object"
            fields:
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Cover", name: "cover", widget: "image"}
              - {label: "Couple (PNG)", name: "couple", widget: "image"}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Τίτλος", name: "title", widget: "string"}
              - {label: "Υπότιτλος", name: "subtitle", widget: "text"}
              - {label: "Chips", name: "chips", widget: "list", field: {label: "Item", name: "item", widget: "string"}}
              - {label: "Lead (δέχεται HTML)", name: "lead", widget: "text"}
          - label: "About"
            name: "about"
            widget: "object"
            fields:
              - {label: "Τίτλος", name: "title", widget: "string"}
              - {label: "Κείμενο 1", name: "p1", widget: "text"}
              - {label: "Κείμενο 2", name: "p2", widget: "text"}
              - {label: "Κείμενο 3", name: "p3", widget: "text"}
          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - {label: "Τηλέφωνο", name: "phone", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Διεύθυνση", name: "address", widget: "string"}
          - {label: "Taglines", name: "taglines", widget: "list", field: {label: "Φράση", name: "phrase", widget: "string"}}
